author = Allin Cottrell
email = cottrell@wfu.edu
version = 1.1
date = 2023-11-27
description = Confidence band plot
tags = C10
min-version = 2018a
gui-main = GUI_bandplot
menu-only = GUI_bandplot
label = Confidence band plot
menu-attachment = MODELWIN/Graphs
model-requirement = ols
public = GUI_bandplot bandplot 
no-print = GUI_bandplot bandplot 
menu-only = GUI_bandplot 
help = bandplot_help.md
gui-help = bpgui.help
sample-script = enroll.inp
