author = Allin Cottrell
email = cottrell@wfu.edu
version = 0.2
date = 2023-03-09
description = Random Forest (via R)
tags = C14 C53
min-version = 2023a
gui-main = GUI_rf
gui-help = rf_gui.md
label = Random Forest
menu-attachment = MAINWIN/Model/RobustModels
bundle-print = rf_print
bundle-plot = rf_plot
R-setup = rf_setup
ui-maker = rf_ui_maker
public = random_forest GUI_rf rf_print rf_plot
help = random_forest.pdf
sample-script = random_forest_sample.inp
data-files = titanic3.gdt
R-depends = R 4.1.0 randomForest 4.7-1.1
