author = Ignacio Diaz-Emparanza and Allin Cottrell
email = cottrell@wfu.edu
version = 2.1
date = 2026-09-14
tags = C53
description = Holt's forecasting method
label = Holt
menu-attachment = MAINWIN/Variable/Filter
min-version = 2025a
data-requirement = needs-time-series-data
public = Holt Holt_gui Holt_plot
gui-main = Holt_gui
gui-precheck = holt_precheck
gui-help = holt_gui_help.md
ui-maker = holt_ui_maker
bundle-plot = Holt_plot
help = Holt.pdf
sample-script = Holt_sample.inp
