author = Allin Cottrell
email = cottrell@wfu.edu
version = 0.1
date = 2026-03-11
tags = C53
description = Holt-Winters
label = Holt-Winters
menu-attachment = MAINWIN/Variable/Filter
min-version = 2025a
data-requirement = needs-time-series-data
public = holt_winters hw_gui
gui-main = hw_gui
gui-precheck = hw_precheck
gui-help = hw_gui_help.md
ui-maker = hw_ui_maker
bundle-plot = hw_plot
help = holt_winters.pdf
data-files = aus_holidays.gdt
sample-script = holt_winters_sample.inp
