author = Ignacio Diaz-Emparanza and Allin Cottrell
email = cottrell@wfu.edu
version = 2.0
date = 2026-04-18
tags = C53
description = Winters
label = Winters
menu-attachment = MAINWIN/Model/TSModels
min-version = 2025a
data-requirement = needs-time-series-data
public = Winters Winters_gui Winters_plot
gui-main = Winters_gui
gui-precheck = winters_precheck
gui-help = winters_gui_help.md
ui-maker = winters_ui_maker
bundle-plot = Winters_plot
help = Winters.pdf
data-files = aus_holidays.gdt
sample-script = Winters_sample.inp
