author = Allin Cottrell
email = cottrell@wfu.edu
version = 2.0
date = 2020-08-15
description = Sequential addition of variables to a model
tags = C20
min-version = 2019a
public = addlist 
help = addlist_help.txt
sample-script = addlist_sample.inp
