author = Allin Cottrell
email = cottrell@wfu.edu
version = 1.0
date = 2025-12-18
description = Hausman-Taylor panel model
tags = C23 C26
min-version = 2023b
data-requirement = needs-panel-data
gui-main = GUI_hausman_taylor
ui-maker = ht_uimaker
label = Hausman-Taylor
menu-attachment = MAINWIN/Model/PanelModels
bundle-print = ht_print
public = hausman_taylor ht_print GUI_hausman_taylor
help = hausman_taylor.pdf
gui-help = ht_gui.md
sample-script = ht_sample.inp
data-files = PSID7682.gdt
