author = Allin Cottrell
email = cottrell@wfu.edu
version = 0.3
date = 2024-10-13
description = Hausman-Taylor panel model
tags = C23 C26
min-version = 2019b
data-requirement = needs-panel-data
gui-main = GUI_hausman_taylor
label = Hausman-Taylor
menu-attachment = MAINWIN/Model/PanelModels
bundle-print = ht_print
public = hausman_taylor ht_print GUI_hausman_taylor
help = hausman_taylor.pdf
sample-script = ht_sample.inp
data-files = PSID7682.gdt
