author = Allin Cottrell
email = cottrell@wfu.edu
version = 0.1
date = 2025-05-17
description = Translation demo
tags = C20
min-version = 2025b
data-requirement = no-data-ok
public = tr_demo tr_demo_gui
gui-main = tr_demo_gui
menu-attachment = MAINWIN/Tools
label = Translation demo
translations = trdemo.xml
help = trdemo_help.txt
sample-script = trdemo_sample.inp
